baseURL: "https://kafanatakma.de/"
languageCode: de-de
title: KT
theme: PaperMod

module:
  imports:
    - path: "github.com/adityatelange/hugo-PaperMod"

params:
    homeInfoParams:
        Title: Kafana Takma
        Content: Deshalb schreib ich hier Sachen rein. Manche mag ich ganz gern, manche nicht so. Irgendwas muss man ja machen und ich mache jetzt mal das.  
    
    ShowReadingTime: false

    ShowPostNavLinks: true

    
menu:
  main:
    - identifier: search
      name: Suche
      url: /search/
      weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary