baseURL: "https://apprenticemoose.github.io/KafanaTakma/"
languageCode: de-de
title: Kafana Takma
theme: github.com/adityatelange/hugo-PaperMod

module:
  imports:
    - path: "github.com/adityatelange/hugo-PaperMod"
